CREATE TABLE IF NOT EXISTS addresses (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT NOT NULL,
postcode TEXT NOT NULL,
prefecture TEXT NOT NULL,
city TEXT NOT NULL,
street TEXT NOT NULL,
apartment TEXT,
phone TEXT NOT NULL,
email TEXT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);